name: Handle new image
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/assets/latest.png'
jobs:
  process_image:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: Process latest image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2-beta
      - name: Install dependencies
        run: npm install --only=production --no-package-lock
      - name: Process image
        run: node ./.github/scripts/publish-image
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          FACEBOOK_ID: ${{ secrets.FACEBOOK_ID }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
      - name: Commit new image
        run: |
          echo "Committing image"
          git config user.name "${{github.actor}}"
          git config user.email "${{github.actor}}@users.noreply.github.com"
          git add ./img/*.png || exit 0
          git commit -m "Saved today's image" -a || exit 0
          git push -f -q
